# Generated by Django 5.0.6 on 2024-06-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_quatity_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='user_id',
            new_name='user',
        ),
    ]
